# ===================================================================
# EXPERIMENT 6: No Expletives + Poor Determiners + Lemmatize Verbs
# GOAL: Test the combined effect of removing expletives, impoverishing determiners, and lemmatizing verbs
# ===================================================================

experiment_name: "exp6_no_expletives_poor_determiners_lemmatize_verbs"

# --- Data Configuration ---
data:
  source_corpus: "data/raw/train_90M/"
  training_corpus: "data/processed/exp6_no_expletives_poor_determiners_lemmatize_verbs/"
  batch_size: 256
  max_sequence_length: 128

# --- Dataset Manipulation Pipeline ---
dataset_manipulation:
  - type: remove_expletives
    input_path: "data/raw/train_90M/"
    output_path: "data/processed/exp6_intermediate_step1/"
    parameters:
      chunk_size: 1000
      replacement_pool_dir: "data/raw/pull_10M/"
      skip_validation: true
      verbose: true
  - type: impoverish_determiners
    input_path: "data/processed/exp6_intermediate_step1/"
    output_path: "data/processed/exp6_intermediate_step2/"
    parameters:
      chunk_size: 1000
      replacement_pool_dir: "data/processed/exp1_remove_expletives/replacement_pool_remainder/"
      skip_validation: true
      verbose: true
  - type: lemmatize_verbs
    input_path: "data/processed/exp6_intermediate_step2/"
    output_path: "data/processed/exp6_no_expletives_poor_determiners_lemmatize_verbs/"
    parameters:
      chunk_size: 1000
      replacement_pool_dir: "data/processed/exp2_no_expletives_poor_determiners/replacement_pool_remainder/"
      skip_validation: true
      verbose: true

# --- Tokenizer Configuration ---
tokenizer:
  output_dir: "tokenizers/exp6_no_expletives_poor_determiners_lemmatize_verbs/"
  vocab_size: 50004

# --- Model Architecture ---
model:
  layers: 12
  embedding_size: 768
  hidden_size: 768
  intermediate_hidden_size: 3072
  attention_heads: 12
  activation_function: "GELU"
  dropout: 0.1
  attention_dropout: 0.1

# --- Training Procedure ---
training:
  output_dir: "models/exp6_no_expletives_poor_determiners_lemmatize_verbs/"
  learning_rate: 0.0001
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-6
  warmup_steps: 10000
  train_steps: 1000000
  checkpointing_strategy: "log_steps_first_epoch"
  epochs: 20

# --- Logging & Reproducibility ---
logging:
  use_wandb: true
  wandb_project: "just-drop-the-subject"
random_seed: 42 