# ===================================================================
# EXPERIMENT 0: Baseline
# GOAL: Train the base model on the unaltered BabyLM corpus.
# This serves as the control against which all ablations are measured.
# ===================================================================

experiment_name: "exp0_baseline_model"

# --- Data Configuration ---
data:
  # Path to the raw, unprocessed training data.
  source_corpus: "data/raw/train_90M/"
  # The final training corpus is the same as the source in this case.
  training_corpus: "data/raw/train_90M/"
  # Configuration for the dataset loader.
  batch_size: 256
  max_sequence_length: 128

# --- Dataset Manipulation Pipeline ---
# This section is empty because this is the baseline experiment.
# No ablations are performed.
dataset_manipulation: []

# --- Tokenizer Configuration ---
tokenizer:
  # Where to save the trained tokenizer for this experiment.
  output_dir: "tokenizers/exp0_baseline/"
  vocab_size: 50004

# --- Model Architecture ---
# Parameters for the GPT-2 model, based on your proposal's Table 5.
model:
  layers: 12
  embedding_size: 768
  hidden_size: 768
  intermediate_hidden_size: 3072
  attention_heads: 12
  activation_function: "GELU"
  dropout: 0.1
  attention_dropout: 0.1

# --- Training Procedure ---
training:
  # Path to save model checkpoints.
  output_dir: "models/exp0_baseline/"
  # Training parameters from Table 5.
  learning_rate: 0.0001
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_epsilon: 1.0e-6
  warmup_steps: 10000
  train_steps: 1000000
  # Custom checkpointing strategy from the proposal.
  checkpointing_strategy: "log_steps_first_epoch"
  epochs: 20

# --- Logging & Reproducibility ---
logging:
  # Integrate with Weights & Biases as per the proposal.
  use_wandb: true
  wandb_project: "just-drop-the-subject"
# A random seed for ensuring reproducibility between experiments.
random_seed: 42